name: Build Android APK

on:
  push:
    branches: [ "main", "основной" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'

      - name: Install Flet CLI
        run: |
          pip install flet

      - name: Build APK
        run: |
          flet build apk --no-analytics

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Medina-App-APK
          path: build/apk/*.apk
