name: Build Android APK

on:
  push:
    branches: [ "main", "основной" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet CLI
        run: |
          pip install "flet[all]"

      - name: Build APK
        env:
          CI: true
        run: |
          flet build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Medina-App-APK
          path: build/apk/*.apk
